"""Configuration for Contamination Estimator."""

CONTAMINATION_THRESHOLD = 0.03
ANGSD_MIN_DEPTH = 1
ANGSD_MIN_MAPQ = 25
ANGSD_MIN_BASEQ = 20

MT_CONSENSUS_MIN_COVERAGE = 3
X_CHROMOSOME_MIN_COVERAGE = 2

BOOTSTRAP_REPS = 200
