"""Configuration for Gene Family Expansion Detector."""

MIN_FOLD_EXPANSION = 2.0
P_VALUE_THRESHOLD = 0.05

CAFE_LAMBDA_ESTIMATE = True
BOOTSTRAP_REPS = 1000

MIN_FAMILY_SIZE = 2
MIN_SPECIES_REPRESENTATION = 3
