"""Configuration for Introgression Detector."""

D_STAT_BLOCK_SIZE = 100
BOOTSTRAP_REPS = 1000
SIGNIFICANCE_THRESHOLD = 0.05
Z_SCORE_THRESHOLD = 3.0

MIN_ABBA_BABA_COUNT = 10
MIN_SNPS_PER_BLOCK = 5

WINDOW_SIZE_KB = 50
STEP_SIZE_KB = 10

F4_RATIO_THRESHOLD = 0.05
