"""Configuration for Paralog Cluster Builder."""

MIN_IDENTITY = 30.0
MIN_COVERAGE = 50.0
MAX_EVALUE = 1e-5

MCL_INFLATION = 2.0
MCL_MIN_CLUSTER_SIZE = 2

TANDEM_WINDOW_KB = 100
SEGDUP_MIN_SIZE_KB = 10
SEGDUP_MIN_IDENTITY = 90.0
