"""Configuration for Effective Population Size Estimator."""

DEFAULT_GENERATION_TIME = 30.0
DEFAULT_MUTATION_RATE = 1.25e-8
DEFAULT_RECOMBINATION_RATE = 1e-8

WATTERSON_CONSTANT_PRECISION = 1000

LD_NE_MAX_DISTANCE_KB = 100
LD_NE_R2_THRESHOLD = 0.1

PSMC_TIME_BINS = 64
PSMC_BOOTSTRAP_REPS = 100

CI_PERCENTILE_LOWER = 2.5
CI_PERCENTILE_UPPER = 97.5
