"""Configuration for Enhancer Target Linker."""

MAX_DISTANCE_BP = 500000
MIN_LINK_SCORE = 0.1

ABC_ACTIVITY_WEIGHT = 0.5
ABC_CONTACT_WEIGHT = 0.5

CORRELATION_MIN_SAMPLES = 10
CORRELATION_R_THRESHOLD = 0.3

DISTANCE_DECAY_EXPONENT = 2.0
