"""Configuration for Gene Circuit Stability Estimator."""

ODE_SOLVER = "RK45"
SIMULATION_TIME_HOURS = 100
TIME_STEPS = 10000

PERTURBATION_FRACTION = 0.1
N_PERTURBATIONS = 100

OSCILLATION_DETECTION_MIN_PERIODS = 3
LYAPUNOV_EXPONENT_THRESHOLD = 0.0
