"""Configuration for Gene Loss Detector."""

MIN_SPECIES_WITH_GENE = 3
MAX_QUERY_COVERAGE_FOR_LOSS = 0.3

PSEUDOGENE_STOP_CODON_DENSITY = 0.01
PSEUDOGENE_FRAMESHIFT_DENSITY = 0.005

BRANCH_LENGTH_THRESHOLD = 0.5
MIN_EXON_COVERAGE = 0.5
