"""Configuration for Population Differentiation Scorer."""

FST_OUTLIER_PERCENTILE = 99.0
BOOTSTRAP_REPS = 1000
MIN_SNPS_PER_WINDOW = 20

DEFAULT_WINDOW_SIZE = 50000
DEFAULT_STEP_SIZE = 10000

WEIR_COCKERHAM = True
