"""Configuration for DNA Fragmentation Profiler."""

ANCIENT_MEAN_LENGTH_THRESHOLD = 80
ANCIENT_CT_RATE_THRESHOLD = 0.15

MAX_FRAGMENT_LENGTH = 500
DEAMINATION_CONTEXT_BASES = 25

MAPQ_THRESHOLD = 25
BASEQ_THRESHOLD = 20
