"""Configuration for Genetic Rescue Candidate Selector."""

MAX_KINSHIP_FOR_RESCUE = 0.25
MIN_HETEROZYGOSITY_GAIN = 0.05

OUTBREEDING_DEPRESSION_KINSHIP_THRESHOLD = 0.0

ECOTYPE_MISMATCH_PENALTY = 0.3
GEOGRAPHIC_DISTANCE_DECAY_KM = 500
