"""Configuration for Splice Impact Predictor."""

DONOR_WINDOW_UPSTREAM = 3
DONOR_WINDOW_DOWNSTREAM = 6

ACCEPTOR_WINDOW_UPSTREAM = 20
ACCEPTOR_WINDOW_DOWNSTREAM = 3

DISRUPTION_DELTA_THRESHOLD = -2.0
CREATION_DELTA_THRESHOLD = 2.0

CANONICAL_DONOR = "GT"
CANONICAL_ACCEPTOR = "AG"

MAX_INTRONIC_DISTANCE = 200
MAX_EXONIC_DISTANCE = 10

SCORE_THRESHOLD = 3.0
