"""Configuration for UTR Variant Analyser."""

KOZAK_CONSENSUS = "GCCACCATG"
KOZAK_UPSTREAM_CONTEXT = 6
KOZAK_DOWNSTREAM_CONTEXT = 3

STRONG_KOZAK_POSITIONS = {-3: "A", -2: "C", -1: "C", 4: "G"}

POLYA_SIGNALS = ["AATAAA", "ATTAAA", "AGTAAA", "TATAAA", "CATAAA", "GATAAA"]
POLYA_DOWNSTREAM_ELEMENT = "TGT"

MIN_UORF_LENGTH = 3
MAX_UORF_SEARCH_WINDOW = 500

IRES_SEARCH_WINDOW = 100
