"""Configuration for Population Viability Genomics Estimator."""

VIABILITY_PERSISTENCE_THRESHOLD = 0.95
QUASI_VIABLE_THRESHOLD = 0.50

TIME_HORIZONS_YEARS = [50, 100, 200]

MVP_GENOMIC_NE = 100
MUTATION_RATE = 1.25e-8
DELETERIOUS_MUTATION_RATE = 0.5

INBREEDING_DEPRESSION_LETHAL_EQUIVALENTS = 3.14
