"""Configuration for Expression Divergence Scorer."""

MIN_EXPRESSION_TPM = 1.0
LOG_FOLD_CHANGE_THRESHOLD = 2.0
JSI_DIVERGENCE_THRESHOLD = 0.5
TAU_THRESHOLD = 0.8

PERMUTATION_REPS = 1000
FDR_THRESHOLD = 0.05
