"""Configuration for Gene Essentiality Predictor."""

ESSENTIAL_SCORE_THRESHOLD = 0.7
CONTEXT_DEPENDENT_SCORE_THRESHOLD = 0.4

LOEUF_ESSENTIAL_THRESHOLD = 0.35
PLI_ESSENTIAL_THRESHOLD = 0.9

CRISPR_ESSENTIAL_THRESHOLD = -1.0
RNAI_ESSENTIAL_THRESHOLD = -1.5

DEPMAP_ESSENTIAL_FRACTION = 0.5
