"""Configuration for Post-Mortem Damage Simulator."""

DEFAULT_MODEL = "briggs"

BRIGGS_NICK_FREQ = 0.024
BRIGGS_DEAMINATION_SS = 0.68
BRIGGS_DEAMINATION_DS = 0.01
BRIGGS_OVERHANG = 2.0

DEFAULT_MEAN_FRAGMENT_LENGTH = 60
DEFAULT_N_READS = 100000

OUTPUT_FORMAT = "fastq"
