"""Configuration for Lineage-Specific Gene Finder."""

MAX_EVALUE_BLAST = 1e-3
MIN_QUERY_COVERAGE = 30.0

MIN_OUTGROUP_SPECIES = 3
MAX_ALLOWED_HITS_IN_OUTGROUP = 0

HGT_INDICATOR_CODON_USAGE_BIAS = True
RAPID_DIVERGENCE_KA_KS_THRESHOLD = 1.5
