"""Configuration for Promoter Variant Scorer."""

PROMOTER_UPSTREAM = 2000
PROMOTER_DOWNSTREAM = 200

IC_THRESHOLD = 8.0
SCORE_THRESHOLD_PERCENTILE = 80.0

DISRUPTION_DELTA_THRESHOLD = -3.0
CREATION_DELTA_THRESHOLD = 3.0

TATA_BOX_CONSENSUS = "TATAAAA"
TATA_BOX_WINDOW = (-35, -25)

CORE_PROMOTER_ELEMENTS = ["TATA", "INRP", "BRE", "DCE", "DPE", "MTE"]
