"""Configuration for Guide RNA Secondary Structure Analyser."""

SCAFFOLD_SEQUENCES: dict[str, str] = {
    "SpCas9": "GTTTTAGAGCTAGAAATAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGAAAAAGTGGCACCGAGTCGGTGC",
    "SaCas9": "GTTTTAGTACTCTGGAAACAGAATCTACTAAAACAAGGCAAAATGCCGTGTTTATCTCGTCAACTTGTTGGCGAGA",
}

SEED_REGION_START = 1
SEED_REGION_END = 12

MFE_UNFAVOURABLE_THRESHOLD = -5.0
ACCESSIBILITY_THRESHOLD = 0.60
