"""Configuration for Chromatin Accessibility Scorer."""

OPEN_CHROMATIN_SCORE_THRESHOLD = 2.0
INTERMEDIATE_SCORE_THRESHOLD = 1.0

Q_VALUE_THRESHOLD = 0.05
MIN_PEAK_LENGTH = 100
MAX_PEAK_LENGTH = 3000

MAPQ_THRESHOLD = 30
FRAGMENT_SIZE_RANGE = (100, 200)
