"""Configuration for Coexpression Module Finder."""

SOFT_THRESHOLD_POWER = 6
MIN_MODULE_SIZE = 30
MERGE_CUT_HEIGHT = 0.25

PEARSON_CORRELATION_THRESHOLD = 0.8
SIGNED_NETWORK = True

MIN_EXPRESSION_MEAN = 1.0
MIN_SAMPLES = 15
