"""Configuration for Genome Rearrangement Mapper."""

MIN_BLOCK_SIZE_KB = 100
MIN_ANCHOR_GENES = 5

BREAKPOINT_FLANKING_WINDOW_KB = 50

INVERSION_MIN_SIZE_KB = 10
TRANSLOCATION_MIN_SIZE_KB = 50
FUSION_FISSION_DETECTION = True
