"""Configuration for Enhancer Conservation Analyser."""

HIGH_CONSERVATION_PHASTCONS = 0.8
MODERATE_CONSERVATION_PHASTCONS = 0.4

HIGH_CONSERVATION_PHYLOP = 2.0
LINEAGE_SPECIFIC_SPECIES_FRACTION = 0.2

ALIGNMENT_MIN_IDENTITY = 60.0
MIN_SPECIES_FOR_HIGH = 10
