"""Configuration for Gene Regulatory Network Builder."""

MIN_EDGE_WEIGHT = 0.01
TOP_EDGES_PER_TARGET = 10

GENIE3_N_TREES = 1000
GENIE3_N_FEATURES_FRACTION = 0.3

ARACNE_MI_THRESHOLD = 0.1
ARACNE_DPI_TOLERANCE = 0.0

CORRELATION_ABS_THRESHOLD = 0.3
FDR_THRESHOLD = 0.05
