"""Configuration for Ancestral Gene Content Reconstructor."""

PARSIMONY_CRITERION = "dollo"
BAYESIAN_MCMC_STEPS = 100000
BAYESIAN_BURNIN = 0.25

GAIN_RATE_PRIOR = 0.01
LOSS_RATE_PRIOR = 0.01

PRESENT_THRESHOLD = 0.8
ABSENT_THRESHOLD = 0.2
