"""Configuration for Promoter Strength Estimator."""

PROMOTER_UPSTREAM = 2000
PROMOTER_DOWNSTREAM = 200

TATA_BOX_IC_THRESHOLD = 5.0
INR_IC_THRESHOLD = 4.0

STRONG_GC_CONTENT_MIN = 0.55
CPG_OE_THRESHOLD = 0.6

STRONG_SCORE_THRESHOLD = 0.7
MODERATE_SCORE_THRESHOLD = 0.4
WEAK_SCORE_THRESHOLD = 0.2
