"""Configuration for Ortholog Mapper."""

RECIPROCAL_BEST_HIT_EVALUE = 1e-10
MIN_SEQUENCE_IDENTITY = 30.0
MIN_COVERAGE = 50.0

SYNTENY_WINDOW = 10
SYNTENY_MIN_COLLINEAR_GENES = 3

BLAST_THREADS = 4
BLAST_MAX_HITS = 5
