"""Configuration for Genome Completeness Estimator."""

DEFAULT_LINEAGE = "vertebrata_odb10"
BUSCO_HMMER_EVALUE = 1e-3
BUSCO_MIN_COMPLETE_FRACTION = 0.95

TRAINING_SPECIES = "human"

HIGH_COMPLETENESS_THRESHOLD = 0.95
ACCEPTABLE_COMPLETENESS_THRESHOLD = 0.80
