"""Configuration for Regulatory Rewiring Analyser."""

MIN_SEQUENCE_CONSERVATION = 0.7
POSITION_CONSERVATION_WINDOW_KB = 50

GAINED_ELEMENT_IDENTITY_THRESHOLD = 0.3
CONSERVED_ELEMENT_IDENTITY_THRESHOLD = 0.7

TFBS_DELTA_THRESHOLD = 3.0
PROMOTER_WINDOW = 2000
