"""Configuration for Inbreeding Risk Forecaster."""

CRITICAL_F_THRESHOLD = 0.25
HIGH_F_THRESHOLD = 0.125

MIN_ROH_LENGTH_KB = 500
ROH_WINDOW_SIZE_KB = 500

CRITICAL_NE_THRESHOLD = 50
HIGH_RISK_NE_THRESHOLD = 100
EFFECTIVE_NE_MULTIPLIER = 0.5
