"""Configuration for Adaptive Diversity Scorer."""

FST_OUTLIER_PERCENTILE = 99.0
MIN_ENVIRONMENTAL_CORRELATION = 0.3

HIGH_ADAPTIVE_DIVERSITY_THRESHOLD = 0.8
LOW_ADAPTIVE_DIVERSITY_THRESHOLD = 0.3

IMMUNE_GENE_CATEGORIES = ["MHC", "innate_immunity", "TLR"]
