"""Configuration for Admixture Signal Scanner."""

K_MIN = 2
K_MAX = 10
CV_FOLDS = 5

CONVERGENCE_TOLERANCE = 1e-4
MAX_ITERATIONS = 10000

ADMIXED_THRESHOLD = 0.1
SEED = 42

LD_PRUNE_WINDOW_KB = 50
LD_PRUNE_STEP = 10
LD_PRUNE_R2 = 0.1
