"""Configuration for Synthetic Promoter Designer."""

DEFAULT_PROMOTER_LENGTH = 200
MIN_PROMOTER_LENGTH = 50
MAX_PROMOTER_LENGTH = 1000

TATA_BOX_POSITION = -30
INR_POSITION = 0

CORE_ELEMENTS = ["TATA", "INR", "BRE", "DPE"]
MAX_TFBS_PER_DESIGN = 8
MIN_SPACING_BETWEEN_TFBS = 6

TARGET_STRENGTH_RANGE = (0.5, 1.0)
