"""Configuration for Founder Effect Estimator."""

DIVERSITY_RATIO_STRONG = 0.5
DIVERSITY_RATIO_MODERATE = 0.7

PRIVATE_VARIANT_FRACTION_STRONG = 0.3
LONG_HAPLOTYPE_BLOCK_KB = 200

GENERATION_TIME = 30.0
MUTATION_RATE = 1.25e-8

BOOTSTRAP_REPS = 200
