"""Configuration for Palaeogenomic Coverage Assessor."""

HIGH_COVERAGE_THRESHOLD = 5.0
MEDIUM_COVERAGE_THRESHOLD = 1.0
LOW_COVERAGE_THRESHOLD = 0.1

MIN_MAPQ = 25
MIN_BASEQ = 20
REMOVE_DUPLICATES = True

BREADTH_THRESHOLDS = [1, 5, 10, 20]
