"""Configuration for Ancestral State Reconstructor."""

DEFAULT_SUBSTITUTION_MODEL = "GTR+G"
GAMMA_CATEGORIES = 4

UNCERTAINTY_THRESHOLD = 0.5
MARGINAL_RECONSTRUCTION = True

BAYESIAN_MCMC_STEPS = 1000000
BAYESIAN_BURNIN = 0.25
