"""Configuration for CRISPR Knock-in Designer."""

ARM_LENGTH_DEFAULT = 100
ARM_LENGTH_MIN = 50
ARM_LENGTH_MAX = 500
MAX_CUT_DISTANCE = 30
PAM_MOTIF_DEFAULT = "NGG"
SPACER_LENGTH = 20

SSODDN_MAX_LENGTH = 200
DSODDN_MIN_LENGTH = 400
