"""Configuration for Genomic Diversity Index."""

DEFAULT_WINDOW_SIZE = 50000
DEFAULT_STEP_SIZE = 10000
MIN_SNPS_PER_WINDOW = 10

MUTATION_RATE = 1.25e-8

FIS_INBREEDING_THRESHOLD = 0.1
TAJIMAS_D_NEUTRALITY_RANGE = (-2.0, 2.0)
