"""Configuration for Contig Scaffolding Helper."""

MIN_LINK_SUPPORT = 3
DEFAULT_GAP_SIZE = 100
MAX_GAP_SIZE = 50000

HIC_MIN_CONTACTS = 5
PAIRED_END_INSERT_SIZE = 500

ORIENTATION_CONFIDENCE_THRESHOLD = 0.7
